name: Deploying Game UI
on: [push]
jobs:
  build:
    name: Deploying Game User Web Interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy
